#page title
page_title                                : Hocbaionha                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1539903206                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : itms-apps://apple.com/app/id1539903206                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : market://details?id=vn.hbon                                          # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Hocbaionha                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Miễn phí                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Hocbaionha là nền tảng giáo dục trực tuyến cho học sinh được hơn 200 trường THCS ở Việt Nam tin tưởng và đưa vào giảng dạy cho nhà trường.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hocbaionha.com                               
your_link                                 : https://hocbaionha.com               
your_city                                 :                                 
email_address                             : info@hocbaionha.com
facebook_username                         : Hocbaionha                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Nội dung chương trình chuẩn mực
    description                           : Chương trình các môn học Toán, Ngữ văn, Tiếng Anh THCS được biên soạn theo cấu trúc Sách giáo khoa của Bộ Giáo dục và Đào tạo, sử dụng song song với chương trình học trên lớp. Ngoài ra còn có các chương trình học Toán, Tiếng Anh và IT theo giáo trình nước ngoài để học sinh nâng cao kiến thức.
    fontawesome_icon_name                 : magic
    
  - title                                 : Phương pháp học tập hiện đại
    description                           : Ứng dụng các phương pháp giảng dạy hiện đại để giúp cho học sinh và giáo viên tiếp cận với các kiến thức cập nhật trên thế giới, tích hợp các công cụ hỗ trợ học sinh tương tác trực tiếp và làm chủ bài học giúp học tập chủ động.
    fontawesome_icon_name                 : star

  - title                                 : Đội ngũ giáo viên chuyên môn cao
    description                           : Chương trình được biên soạn và kiểm duyệt bởi đội ngũ thầy cô giáo là các Tiến sĩ, Thạc sĩ có trình độ chuyên môn và kinh nghiệm giảng dạy lâu năm.
    fontawesome_icon_name                 : graduation-cap

  - title                                 : Công nghệ tiên tiến
    description                           : Ứng dụng các công nghệ giáo dục tiên tiến nhất hiện nay trên thế giới để tạo một môi trường học tập hiệu quả, thân thiện, đa nền tảng và cá nhân hoá lộ trình học tập cho từng học sinh. Các tính năng độc quyền được phát triển cũng giúp giáo viên dễ dàng kết nối, giao bài tập và theo dõi tình hình học tập của học sinh một cách đơn giản và thiết thực.
    fontawesome_icon_name                 : bolt
  
  - title                                 : Hỗ trợ và đồng hành với người dùng
    description                           : Đội ngũ hỗ trợ luôn theo sát để giải đáp, hướng dẫn và định hướng học tập cho học sinh, phụ huynh, giáo viên trong suốt quá trình sử dụng.
    fontawesome_icon_name                 : phone-square-alt


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown