#page title
page_title                                : Hocbaionha                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1539903206                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : itms-apps://apple.com/app/id1539903206                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : market://details?id=vn.hbon                                          # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Hocbaionha                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Miễn phí                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Hocbaionha là nền tảng giáo dục trực tuyến được tin tưởng bởi hơn 100 trường THCS ở Việt Nam.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hocbaionha.com                               
your_link                                 : https://hocbaionha.com               
your_city                                 :                                 
email_address                             : info@hocbaionha.com
facebook_username                         : Hocbaionha                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Nội dung giáo dục toàn diện
    description                           : Chương trình phổ thông chính khóa của Bộ GD và Đào tạo các chuẩn mực giáo dục và sư phạm hiện đại. Bài học, bài tập tương tác, trải nghiệm mô phỏng, chương trình luyện thi với cách thức truyền tải đa phương tiện
    fontawesome_icon_name                 : magic
    
  - title                                 : Ứng dụng công nghệ tiên tiến
    description                           : Ứng dụng những công nghệ tiên tiến và phổ biến trên thế giới trong lĩnh vực giáo dục để xây dựng hệ thống và các nội dung số.
    fontawesome_icon_name                 : star

  - title                                 : Dịch vụ hỗ trợ người dùng
    description                           : Cung cấp dịch vụ hỗ trợ học sinh học tập qua tin nhắn trên hệ thống và dịch vụ đào tạo, tập huấn, hướng dẫn, và hỗ trợ giáo viên.
    fontawesome_icon_name                 : info-circle


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown